"""
Django settings for middleware project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from typing import TypedDict, Literal, Dict, cast

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-81zlu#4y@$3$+ma$-hga^7$gq778pz+(a5rs8yv=+$mms9afs4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'registration',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup',
    'django_ckeditor_5', 
    'core',
    'original_message',
    'unit_message',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'middleware.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'middleware.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "middleware_odoo",
        "USER": "netdata",
        "PASSWORD": "S0port31",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-MX'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

#Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'bold', 'italic', 'link', 'underline', 'bulletedList', 'numberedList',
            'blockQuote', 'undo', 'redo'
        ],
        'height': 300,
        'width': '100%',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ]
    }
}

#Ckeditor Upload path
#CKEDITOR_UPLOAD_PATH='uploads/'

LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:home'


if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")
else:
    #Aqui va la configuración del email en producción
    pass

















ODOO_URL = config("ODOO_URL")
ODOO_DB = config("ODOO_DB")
ODOO_USER = config("ODOO_USER")
ODOO_PASSWORD = config("ODOO_PASSWORD")

PROVIDER_MODE = config("PROVIDER_MODE", default="local")  # local|api|xml
PROVIDER_JSON = config("PROVIDER_JSON", default="data/sample_products.json")
PROVIDER_CSV = config("PROVIDER_CSV", default="data/sample_products.csv")
PROVIDER_API_URL = config("PROVIDER_API_URL", default="")
PROVIDER_API_TOKEN = config("PROVIDER_API_TOKEN", default="")

BATCH_SIZE = config("BATCH_SIZE", cast=int, default=100)
RETRY_LIMIT = config("RETRY_LIMIT", cast=int, default=3)

SQLITE_PATH = "middleware_staging.sqlite"

CREDENTIALS_MYSQL = {
    "host-middleware": config("HOST_MIDDLEWARE"),
    "user-middleware": config("USER_MIDDLEWARE"),
    "password-middleware": config("PASSWORD_MIDDLEWARE"),
    "database-middleware": config("DATABASE_MIDDLEWARE")
}

URL = config("CT_URL", default="")
FTP_HOST = config("CT_HOST", default="")
FTP_USER = config("CT_USER", default="")
FTP_PASSWORD = config("CT_PASS", default="")
FTP_DIRECTORY = config("CT_DIR", default="")
XML_FILE = config("CT_XML", default="")











COMMON_ENDPOINT: str = f"{ODOO_URL}/xmlrpc/2/common"
OBJECT_ENDPOINT: str = f"{ODOO_URL}/xmlrpc/2/object"


class OdooCredentials(TypedDict):
    url: str
    db: str
    user: str
    password: str
    common: str
    object: str


CREDENTIALS: OdooCredentials = {
    "url": ODOO_URL,
    "db": ODOO_DB,
    "user": ODOO_USER,
    "password": ODOO_PASSWORD,
    "common": COMMON_ENDPOINT,
    "object": OBJECT_ENDPOINT,
}


class GeneralSettings(TypedDict):
    DEFAULT_HEADERS: Dict[str, str]
    DEFAULT_IMAGE: str
    DEFAULT_SEARCH: str


class ProvidersRedirects(TypedDict):
    EXCHANGE: str
    CATEGORIES: str
    CATEGORY_PRODUCTS: str


class ProviderData(TypedDict):
    URL: str
    TOKEN: str
    REDIRECTS: ProvidersRedirects


ProviderNames = Literal["SYS"]


SETTINGS: GeneralSettings = {
    "DEFAULT_HEADERS": {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
        ),
    },
    "DEFAULT_IMAGE": cast(str, config("NDS_DEF_IMG")),
    "DEFAULT_SEARCH": cast(str, config("NDS_DEF_SEARCH")),
}


PROVIDERS: Dict[ProviderNames, ProviderData] = {
    "SYS": {
        "URL": cast(str, config("SYS_URL")),
        "TOKEN": cast(str, config("SYS_TOKEN")),
        "REDIRECTS": {
            "EXCHANGE": "/tipocambio",
            "CATEGORIES": "/categorias",
            "CATEGORY_PRODUCTS": "/productos/?categoria={}&pagina={}",
        },
    },
    "CT": {
        "URL": cast(str, config("CT_URL")),
        "TOKEN": cast(str, config("CT_TOKEN")),
        "REDIRECTS": {
            "TOKEN": "/cliente/token",
            "EXCHANGE": "/tipocambio",
            "CATEGORIES": "/categorias",
            "CATEGORY_PRODUCTS": "/productos/?categoria={}&pagina={}",
        },
    },
}


def build_headers(provider: ProviderNames) -> dict[str, str]:
    token = PROVIDERS[provider]["TOKEN"]

    if provider == "SYS":
        header = {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
            ),
            "Content-Type": "application/json",
            "Authorization": "Bearer {}".format(token),
        }
    elif provider == "CT":
        header = {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
            ),
            "Content-Type": "application/json",
            "Authorization": "Bearer {}".format(token),
        }

    else:
        raise ValueError(
            f"Proveedor '{provider}' no está soportado aún en build_headers()"
        )

    return header