# Generated by Django 5.2.7 on 2025-11-04 17:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unit_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField(blank=True, default=None, null=True, verbose_name='Mensaje unitario')),
                ('original_message_id', models.IntegerField(verbose_name='ID Mensaje Original')),
                ('entity', models.CharField(max_length=50, verbose_name='Entidad')),
                ('status', models.CharField(max_length=5, verbose_name='Estatus')),
                ('active', models.IntegerField(verbose_name='Activo')),
                ('response', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Response')),
                ('run_at', models.IntegerField(verbose_name='Run at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Unit Message',
                'verbose_name_plural': 'Unit Message',
                'ordering': ['-updated_at'],
                'permissions': [('can_edit_unit_message', 'Puede hacer todo en unit message')],
            },
        ),
    ]
