# Generated by Django 5.2.7 on 2025-11-11 09:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('original_message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original_message',
            name='request',
        ),
        migrations.AddField(
            model_name='original_message',
            name='request_old',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Request'),
            preserve_default=False,
        ),
    ]
