# Generated by Django 5.2.7 on 2025-11-11 09:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original_message', '0002_remove_original_message_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_message',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='original_message',
            name='request_old',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Request'),
        ),
    ]
