# Generated by Django 5.2.7 on 2025-11-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('original_message', '0003_original_message_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original_message',
            name='request_old',
        ),
    ]
