# Generated by Django 5.2.7 on 2025-11-01 13:49

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='original_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=350, verbose_name='Archivo')),
                ('entity', models.CharField(max_length=50, verbose_name='Entidad')),
                ('status', models.CharField(max_length=2, verbose_name='Estado')),
                ('request', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Request')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Original Message',
                'verbose_name_plural': 'Original Message',
                'ordering': ['-updated_at'],
                'permissions': [('can_edit_original_message', 'Puede hacer todo en original message')],
            },
        ),
    ]
